backend:
  name: git-gateway
media_folder: source/images
public_folder: images
collections:
  - name: posts
    label: Post
    sort: 'date:desc'
    description: >
      The description is a great place for tone setting, high level information,
      and editing guidelines that are specific to a collection.
    folder: _posts
    slug: '{{slug}}'
    create: true
    fields:
      - label: Title
        name: title
        widget: string
        tagname: h1
      - label: Banner
        name: banner
        widget: image
        class: image featured
      - label: Short Description
        name: shortdesc
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta:
      - label: Publish Date
        name: date
        widget: datetime
      - label: Categories
        name: categories
        widget: string
      - label: Layout
        name: layout
        widget: hidden
        default: post
